# Machine Learning 201

## Multiple Linear Regression Models 

* Temel amaç, bğımlı ve bağımsız değişkenler arasındaki ilişkiyi ifade eden doğrusal fonksiyonu bulmaktır.

### Linear Regresion  Assumptions

* Hatalar normal dağılır.
* Hatalar birbirinden bağımsızdır ve aralarında otokorelasyon yoktur.
* Her bir gözlem için hata terimler varyansları sabittir.
* Değişkenler ile hata terimi arasında ilişki yoktur.
* Bağımsız değişkenler arasında çoklu doğrusal ilişki problemi yoktur.

### Advantages and Disadvantages of Regression Models 

- Advantages
    * İyi anlaşılırsa diğer tm ML ve DL konuları çok rahat kavranır.
    * Doğrusallık nedensellik yorumları yapılabilmesini sağlar, bu durum aksiyoner ve stratejik modelleme imkanı verir.
    * Değişkenlerin etki düzeyleri ve anlamlılıkları değerlendirilebilir.
    * Bağımlı değişkendeki değişkenliğin açıklanma başarısı ölçülebilir.
    * Model anlamlılığı değerlendirliebilir
- Disadvantages 
    - Varsayımları vardır.
    - Aykırı gözlemlere duyarlıdır.

### Model

In [2]:
import pandas as pd
df = pd.read_csv("Advertising.csv")
df = df.iloc[:,1:5]
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [3]:
X = df.drop("sales", axis = 1) # bağımsız değişkenler
Y = df[["sales"]] # bağımlı değişken

In [4]:
# Statsmodels ile model kurmak

In [5]:
import statsmodels.api as sm

In [6]:
lm = sm.OLS(Y,X) # regresyon modelini kurmak için gerekli olan fonksiyon

In [7]:
model = lm.fit() # modeli kur

In [8]:
model.summary()

# R-squared : Bağımsız değişkenlerin, bağımlı değişkendeki değişkenliği açıklama yüzdesidir.
# Adj. R-squared : R kare değerinin düzeltilmiş halidir. 
# F-statistic : Modelin anlamlılığını test etmek için kullanılan istatistiktir.
# Prob (F-statistic) : F-statisticliğine ilişkin p-value değeridir. 0.05'den küçük olduğu için modelin anlamlı olduğu bilgisini veriyor.

# coef : Kurulucak denklemde bağımsız değişkenlerin katsayılarını ifade eder.
# std err : coef katsayılarının standart hatalarıdır.
# t ve P>|T|: Elimizdeki katsayı anlamlı mı değil mi diye test ettiğimizde kullanılırlar. Modellemek için kullandığımı bütün değişkenler anlamlıdır(0.05'ten küçük). 

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                  sales   R-squared (uncentered):                   0.982
Model:                            OLS   Adj. R-squared (uncentered):              0.982
Method:                 Least Squares   F-statistic:                              3566.
Date:                Sun, 03 Oct 2021   Prob (F-statistic):                   2.43e-171
Time:                        15:50:04   Log-Likelihood:                         -423.54
No. Observations:                 200   AIC:                                      853.1
Df Residuals:                     197   BIC:                                      863.0
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
TV             0.0538      0.001     40.507      0.000       0.051       0.056
radio          0.2222      0.009     23.595      0.000       0.204       0.241
newspaper      0.0168      0.007      2.517      0.013       0.004       0.030
==============================================================================
Omnibus:                        5.982   Durbin-Watson:                   2.038
Prob(Omnibus):                  0.050   Jarque-Bera (JB):                7.039
Skew:                          -0.232   Prob(JB):                       0.0296
Kurtosis:                       3.794   Cond. No.                         12.6
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [9]:
# scikit learn ile model kurmak

In [10]:
from sklearn.linear_model import LinearRegression

In [11]:
lm = LinearRegression()

In [12]:
model = lm.fit(X,Y)

In [13]:
model.intercept_ # sabit

array([2.93888937])

In [14]:
model.coef_ # bağımsız değişkenlerin katsayılar

array([[ 0.04576465,  0.18853002, -0.00103749]])

### Tahmin 

In [15]:
# Sales = 2.94 + TV * 0.04 + radio * 0.19 - newspaper * 0.001

In [16]:
# 30 birim TV, 10 birim radio, 40 birim newspaper

In [17]:
2.94 + 30 * 0.04 + 10 * 0.19 - 40 * 0.001

5.999999999999999

In [18]:
yeni_veri = [[30],[10],[40]]

In [19]:
yeni_veri = pd.DataFrame(yeni_veri).T

In [20]:
yeni_veri

0   1   2
0  30  10  40

In [21]:
model.predict(yeni_veri)

array([[6.15562918]])

###  Artıklar

In [22]:
from sklearn.metrics import mean_squared_error

In [23]:
Y.head() # gerçek değerler

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [24]:
model.predict(X)[0:10] # tahmin edilen değerler

array([[20.52397441],
       [12.33785482],
       [12.30767078],
       [17.59782951],
       [13.18867186],
       [12.47834763],
       [11.72975995],
       [12.12295317],
       [ 3.72734086],
       [12.55084872]])

In [25]:
MSE = mean_squared_error(Y,model.predict(X))
MSE

2.784126314510936

In [26]:
import numpy as np
RMSE = np.sqrt(MSE)
RMSE

1.6685701407225697

### Model Tuning (Model Doğrulama) 

In [27]:
# Çoklu doğrusal regresyon modelinde hiperparametre olmadığından model tuning işleminden ziyade model doğrulama işlemi yapılacak

In [28]:
X.head()

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [29]:
Y.head()

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [30]:
# Sınama Seti - Holdout

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.20, random_state = 1)

In [33]:
X_train.head()

TV  radio  newspaper
108   13.1    0.4       25.6
107   90.4    0.3       23.2
189   18.7   12.1       23.4
14   204.1   32.9       46.0
56     7.3   28.1       41.4

In [34]:
Y_train.head()

sales
108    5.3
107    8.7
189    6.7
14    19.0
56     5.5

In [35]:
X_test.head()

TV  radio  newspaper
58   210.8   49.6       37.7
40   202.5   22.3       31.6
34    95.7    1.4        7.4
102  280.2   10.1       21.4
184  253.8   21.3       30.0

In [36]:
Y_test.head()

sales
58    23.8
40    16.6
34     9.5
102   14.8
184   17.6

In [37]:
lm = LinearRegression()
model = lm.fit(X_train, Y_train)

In [38]:
# train hatası
np.sqrt(mean_squared_error(Y_train, model.predict(X_train)))

1.736902590147092

In [39]:
# test hatası
np.sqrt(mean_squared_error(Y_test, model.predict(X_test)))

1.411341755858159

In [40]:
# k fold cross validation

In [41]:
from sklearn.model_selection import cross_val_score

In [42]:
# MSE (train seti hatası)
np.mean(-cross_val_score(model, X_train, Y_train, cv = 10, scoring = "neg_mean_squared_error"))

3.1877115209443576

In [43]:
# RMSE
np.sqrt(np.mean(-cross_val_score(model, X_train, Y_train, cv = 10, scoring = "neg_mean_squared_error")))

1.7854163438661463

In [44]:
# Test ve trainin vermiş olduğu hatadan daha doğru bir hata ölçüsü verir
np.sqrt(np.mean(-cross_val_score(model, X, Y, cv = 10, scoring = "neg_mean_squared_error")))

1.7492763126843385